// Generated by gencpp from file jog_msgs/JogJoint.msg
// DO NOT EDIT!


#ifndef JOG_MSGS_MESSAGE_JOGJOINT_H
#define JOG_MSGS_MESSAGE_JOGJOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace jog_msgs
{
template <class ContainerAllocator>
struct JogJoint_
{
  typedef JogJoint_<ContainerAllocator> Type;

  JogJoint_()
    : header()
    , joint_names()
    , deltas()  {
    }
  JogJoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joint_names(_alloc)
    , deltas(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _deltas_type;
  _deltas_type deltas;





  typedef boost::shared_ptr< ::jog_msgs::JogJoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jog_msgs::JogJoint_<ContainerAllocator> const> ConstPtr;

}; // struct JogJoint_

typedef ::jog_msgs::JogJoint_<std::allocator<void> > JogJoint;

typedef boost::shared_ptr< ::jog_msgs::JogJoint > JogJointPtr;
typedef boost::shared_ptr< ::jog_msgs::JogJoint const> JogJointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jog_msgs::JogJoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jog_msgs::JogJoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jog_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'jog_msgs': ['/home/nicolas/catkin_ws/src/jog_arm/jog_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jog_msgs::JogJoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jog_msgs::JogJoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jog_msgs::JogJoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jog_msgs::JogJoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jog_msgs::JogJoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jog_msgs::JogJoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jog_msgs::JogJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d2aa14be64b51cf6374d198bfd489b2";
  }

  static const char* value(const ::jog_msgs::JogJoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d2aa14be64b51cfULL;
  static const uint64_t static_value2 = 0x6374d198bfd489b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::jog_msgs::JogJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jog_msgs/JogJoint";
  }

  static const char* value(const ::jog_msgs::JogJoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jog_msgs::JogJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is a message to hold data to jog by specifying joint\n\
# displacement. You only need to set relative displacement to joint\n\
# angles (or displacements for linear joints).\n\
\n\
# header message. You must set frame_id to define the reference\n\
# coordinate system of the displacament\n\
Header header\n\
\n\
# Name list of the joints. You don't need to specify all joint of the\n\
# robot. Joint names are case-sensitive.\n\
string[] joint_names\n\
\n\
# Relative displacement of the joints to jog. The order must be\n\
# identical to joint_names. Unit is in radian for revolutive joints,\n\
# meter for linear joints.\n\
float64[] deltas\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::jog_msgs::JogJoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jog_msgs::JogJoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joint_names);
      stream.next(m.deltas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JogJoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jog_msgs::JogJoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jog_msgs::JogJoint_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "deltas[]" << std::endl;
    for (size_t i = 0; i < v.deltas.size(); ++i)
    {
      s << indent << "  deltas[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.deltas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOG_MSGS_MESSAGE_JOGJOINT_H
